# Generated by Django 5.2 on 2025-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="date",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
