# Generated by Django 5.2.1 on 2025-05-16 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicerequest_is_rated_alter_service_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="is_rated",
        ),
        migrations.AlterField(
            model_name="service",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="ServiceRating",
        ),
    ]
